# Generated by Django 3.2.6 on 2021-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancelada'), ('A', 'Activa'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
