# Generated by Django 3.2.6 on 2021-08-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='barbero',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activa'), ('C', 'Cancelada'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
