# Generated by Django 3.2.6 on 2021-08-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_auto_20210828_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='telefono',
            field=models.IntegerField(max_length=8, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancelada'), ('A', 'Activa'), ('P', 'Pagada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=8, verbose_name='Telefono'),
        ),
    ]
