# Generated by Django 3.2.6 on 2021-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_auto_20210830_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activa'), ('P', 'Pagada'), ('C', 'Cancelada')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
