# Generated by Django 3.2.6 on 2021-08-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_auto_20210830_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('C', 'Cancelada'), ('P', 'Pagada'), ('A', 'Activa')], default='A', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
